name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: rean_cloud
          MYSQL_USER: admin
          MYSQL_PASSWORD: Qwe445566
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django mysqlclient Pillow

    - name: Run Django system checks
      run: |
        python manage.py check

    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/ubuntu/course_platform
          ./update_settings.sh
          sudo ./nginx_setup.sh
          # Restart Gunicorn (adjust command as needed)
          pkill gunicorn || true
          gunicorn --bind 0.0.0.0:8000 course_platform.wsgi:application &

